// <auto-generated />
using Entities.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(FilmFinityDbContext))]
    [Migration("20200601132543_AddMoviePage")]
    partial class AddMoviePage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.ActorsList", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("ActorsLists");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 11
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 12
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 13
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 14
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 15
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 16
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 17
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 18
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 19
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 20
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 21
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 22
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 23
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 24
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 25
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 26
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 27
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 28
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 29
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 30
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 31
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 32
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 33
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 34
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 35
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 36
                        });
                });

            modelBuilder.Entity("Entities.Models.CelebrityJobTitles", b =>
                {
                    b.Property<int>("CelebrityId")
                        .HasColumnType("int");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("int");

                    b.HasKey("CelebrityId", "JobTitleId");

                    b.HasIndex("JobTitleId");

                    b.ToTable("CelebrityJobTitles");

                    b.HasData(
                        new
                        {
                            CelebrityId = -1,
                            JobTitleId = 1
                        },
                        new
                        {
                            CelebrityId = -2,
                            JobTitleId = 1
                        },
                        new
                        {
                            CelebrityId = -2,
                            JobTitleId = 4
                        },
                        new
                        {
                            CelebrityId = -3,
                            JobTitleId = 1
                        },
                        new
                        {
                            CelebrityId = -3,
                            JobTitleId = 4
                        },
                        new
                        {
                            CelebrityId = -4,
                            JobTitleId = 1
                        },
                        new
                        {
                            CelebrityId = -4,
                            JobTitleId = 2
                        },
                        new
                        {
                            CelebrityId = -4,
                            JobTitleId = 4
                        },
                        new
                        {
                            CelebrityId = -5,
                            JobTitleId = 1
                        },
                        new
                        {
                            CelebrityId = -5,
                            JobTitleId = 4
                        },
                        new
                        {
                            CelebrityId = -6,
                            JobTitleId = 1
                        },
                        new
                        {
                            CelebrityId = -6,
                            JobTitleId = 4
                        },
                        new
                        {
                            CelebrityId = -7,
                            JobTitleId = 1
                        },
                        new
                        {
                            CelebrityId = -7,
                            JobTitleId = 2
                        },
                        new
                        {
                            CelebrityId = -7,
                            JobTitleId = 3
                        },
                        new
                        {
                            CelebrityId = -7,
                            JobTitleId = 4
                        },
                        new
                        {
                            CelebrityId = -8,
                            JobTitleId = 5
                        },
                        new
                        {
                            CelebrityId = -9,
                            JobTitleId = 6
                        },
                        new
                        {
                            CelebrityId = -10,
                            JobTitleId = 1
                        },
                        new
                        {
                            CelebrityId = -10,
                            JobTitleId = 2
                        },
                        new
                        {
                            CelebrityId = -10,
                            JobTitleId = 3
                        },
                        new
                        {
                            CelebrityId = -10,
                            JobTitleId = 4
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            ActorName = "Том Харпер"
                        },
                        new
                        {
                            ActorId = 2,
                            ActorName = "Филисити Джонс"
                        },
                        new
                        {
                            ActorId = 3,
                            ActorName = "Эдди Редмейн"
                        },
                        new
                        {
                            ActorId = 4,
                            ActorName = "Химет Патель"
                        },
                        new
                        {
                            ActorId = 5,
                            ActorName = "Режиссер"
                        },
                        new
                        {
                            ActorId = 6,
                            ActorName = "Джордж Маккей"
                        },
                        new
                        {
                            ActorId = 7,
                            ActorName = "Дин-Чарльз Чакман"
                        },
                        new
                        {
                            ActorId = 8,
                            ActorName = "Ричард Мэдден"
                        },
                        new
                        {
                            ActorId = 9,
                            ActorName = "Джордж Нолфи"
                        },
                        new
                        {
                            ActorId = 10,
                            ActorName = "Энтони Маки"
                        },
                        new
                        {
                            ActorId = 11,
                            ActorName = "Сэмюел Лерой Джексон"
                        },
                        new
                        {
                            ActorId = 12,
                            ActorName = "Ниа Лонг"
                        },
                        new
                        {
                            ActorId = 13,
                            ActorName = "Джейк Кэздан"
                        },
                        new
                        {
                            ActorId = 14,
                            ActorName = "Дуэйн Джонсон"
                        },
                        new
                        {
                            ActorId = 15,
                            ActorName = "Карен Гиллан"
                        },
                        new
                        {
                            ActorId = 16,
                            ActorName = "Джейк Блэк"
                        },
                        new
                        {
                            ActorId = 17,
                            ActorName = "Кевин Харт"
                        },
                        new
                        {
                            ActorId = 18,
                            ActorName = "Джефф Фаулер"
                        },
                        new
                        {
                            ActorId = 19,
                            ActorName = "Джим Керри"
                        },
                        new
                        {
                            ActorId = 20,
                            ActorName = "Джеймс Марсден"
                        },
                        new
                        {
                            ActorId = 21,
                            ActorName = "Тика Самптер"
                        },
                        new
                        {
                            ActorId = 22,
                            ActorName = "Бен Шварц"
                        },
                        new
                        {
                            ActorId = 23,
                            ActorName = "Мэти Янь"
                        },
                        new
                        {
                            ActorId = 24,
                            ActorName = "Марго Робби"
                        },
                        new
                        {
                            ActorId = 25,
                            ActorName = "Джерни Смоллет-Белл"
                        },
                        new
                        {
                            ActorId = 26,
                            ActorName = "Мэри Элизабет"
                        },
                        new
                        {
                            ActorId = 27,
                            ActorName = "Грета Гервич"
                        },
                        new
                        {
                            ActorId = 28,
                            ActorName = "Сирта Ронан"
                        },
                        new
                        {
                            ActorId = 29,
                            ActorName = "Тимоти Шаламе"
                        },
                        new
                        {
                            ActorId = 30,
                            ActorName = "Флоренс Пью"
                        },
                        new
                        {
                            ActorId = 31,
                            ActorName = "Эмма Уотсон"
                        },
                        new
                        {
                            ActorId = 32,
                            ActorName = "Сирзат Яхуп"
                        },
                        new
                        {
                            ActorId = 33,
                            ActorName = "Ху Цзюнь"
                        },
                        new
                        {
                            ActorId = 34,
                            ActorName = "Юань Цуань"
                        },
                        new
                        {
                            ActorId = 35,
                            ActorName = "Берик Айтжанов"
                        },
                        new
                        {
                            ActorId = 36,
                            ActorName = "Аружан Джазильбек"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Celebrity", b =>
                {
                    b.Property<int>("CelebrityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountViews")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CelebrityId");

                    b.ToTable("Celebrities");

                    b.HasData(
                        new
                        {
                            CelebrityId = -1,
                            CountViews = 134000,
                            FirstName = "Хью",
                            ImageSource = "StaticFiles/images/1.jpg",
                            LastName = "Джекман"
                        },
                        new
                        {
                            CelebrityId = -2,
                            CountViews = 127000,
                            FirstName = "Райан",
                            ImageSource = "StaticFiles/images/2.jpg",
                            LastName = "Рейнольдс"
                        },
                        new
                        {
                            CelebrityId = -3,
                            CountViews = 126000,
                            FirstName = "Роберт",
                            ImageSource = "StaticFiles/images/3.jpg",
                            LastName = "Дауни (младший)"
                        },
                        new
                        {
                            CelebrityId = -4,
                            CountViews = 121000,
                            FirstName = "Уилл",
                            ImageSource = "StaticFiles/images/4.jpg",
                            LastName = "Смит"
                        },
                        new
                        {
                            CelebrityId = -5,
                            CountViews = 120500,
                            FirstName = "Брэд",
                            ImageSource = "StaticFiles/images/5.jpg",
                            LastName = "Питт"
                        },
                        new
                        {
                            CelebrityId = -6,
                            CountViews = 120000,
                            FirstName = "Леонардо",
                            ImageSource = "StaticFiles/images/6.jpg",
                            LastName = "Ди Каприо"
                        },
                        new
                        {
                            CelebrityId = -7,
                            CountViews = 91000,
                            FirstName = "Натали",
                            ImageSource = "StaticFiles/images/7.jpg",
                            LastName = "Портман"
                        },
                        new
                        {
                            CelebrityId = -8,
                            CountViews = 20000,
                            FirstName = "Роджер",
                            ImageSource = "StaticFiles/images/8.jpg",
                            LastName = "Дикинс"
                        },
                        new
                        {
                            CelebrityId = -9,
                            CountViews = 50000,
                            FirstName = "Ханс",
                            ImageSource = "StaticFiles/images/9.png",
                            LastName = "Циммер"
                        },
                        new
                        {
                            CelebrityId = -10,
                            CountViews = 95000,
                            FirstName = "Квентин",
                            ImageSource = "StaticFiles/images/10.jpg",
                            LastName = "Тарантино"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.JobTitle", b =>
                {
                    b.Property<int>("JobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobTitleId");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            JobTitleId = 1,
                            JobName = "актер"
                        },
                        new
                        {
                            JobTitleId = 2,
                            JobName = "режиссер"
                        },
                        new
                        {
                            JobTitleId = 3,
                            JobName = "сценарист"
                        },
                        new
                        {
                            JobTitleId = 4,
                            JobName = "продюсер"
                        },
                        new
                        {
                            JobTitleId = 5,
                            JobName = "оператор"
                        },
                        new
                        {
                            JobTitleId = 6,
                            JobName = "композитор"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountStars")
                        .HasColumnType("int");

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CountStars = 5,
                            ImageSource = "StaticFiles/images/11.jpg",
                            MovieTitle = "Аэронавты",
                            ReleaseYear = 2019
                        },
                        new
                        {
                            MovieId = 2,
                            CountStars = 5,
                            ImageSource = "StaticFiles/images/12.jpg",
                            MovieTitle = "1917",
                            ReleaseYear = 2019
                        },
                        new
                        {
                            MovieId = 3,
                            CountStars = 5,
                            ImageSource = "StaticFiles/images/13.jpg",
                            MovieTitle = "Джуманджи: Новый уровень",
                            ReleaseYear = 2019
                        },
                        new
                        {
                            MovieId = 4,
                            CountStars = 5,
                            ImageSource = "StaticFiles/images/14.jpg",
                            MovieTitle = "Банкир",
                            ReleaseYear = 2020
                        },
                        new
                        {
                            MovieId = 5,
                            CountStars = 5,
                            ImageSource = "StaticFiles/images/15.jpg",
                            MovieTitle = "Соник в кино",
                            ReleaseYear = 2020
                        },
                        new
                        {
                            MovieId = 6,
                            CountStars = 5,
                            ImageSource = "StaticFiles/images/16.jpg",
                            MovieTitle = "Хищные птицы: Потрясающая история Харли Квинн",
                            ReleaseYear = 2020
                        },
                        new
                        {
                            MovieId = 7,
                            CountStars = 5,
                            ImageSource = "StaticFiles/images/17.jpg",
                            MovieTitle = "Маленькие женщины",
                            ReleaseYear = 2019
                        },
                        new
                        {
                            MovieId = 8,
                            CountStars = 5,
                            ImageSource = "StaticFiles/images/18.jpg",
                            MovieTitle = "Композитор",
                            ReleaseYear = 2019
                        });
                });

            modelBuilder.Entity("Entities.Models.ActorsList", b =>
                {
                    b.HasOne("WebAPI.Models.Actor", "Actor")
                        .WithMany("ActorsList")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Movie", "Movie")
                        .WithMany("ActorsList")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.CelebrityJobTitles", b =>
                {
                    b.HasOne("WebAPI.Models.Celebrity", "Celebrity")
                        .WithMany("CelebrityJobTitles")
                        .HasForeignKey("CelebrityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.JobTitle", "JobTitle")
                        .WithMany("CelebrityJobTitles")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
